### PR TITLE
WIP: Add wasi_ephemeral_crypto.witx module

### PR DESCRIPTION
**Pull request by ueno**
This adds functions for symmetric encryption algorithms as a start.

See enarx/enarx#119.

### CODE REVIEW

**Comment by ueno** [comment]
To actually play with this interface, I guess both the `wasi` crate (the Rust binding) and wasmtime. I'm currently experimenting the former:
https://github.com/ueno/rust-wasi/commits/wip/dueno/modular

**Comment by ueno** [comment]
@steveeJ @npmccallum could you take a look when you have time? Now you can actually run a test program with a modified wasmtime, following the instruction in https://github.com/ueno/wasmtime/pull/1.

**Comment by npmccallum** [comment]
@ueno I just synced master with the WASI branch. Can you rebase this and I'll review promptly.

**Comment by npmccallum** [comment]
@ueno I think working upstream is the right course of action here. Should we close this PR and delete this repo?

**Comment by ueno** [comment]
I agree; closing this now.

**Pull request closed without merging**
